[tool.poetry]
name = "tsrc"
version = "2.2.0"
description = "Manage groups of git repositories"
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
readme = "README.rst"
license = "BSD-3-Clause"
repository = "https://github.com/TankerHQ/tsrc"
documentation = "https://tankerhq.github.io/tsrc"

[tool.poetry.dev-dependencies]
pygit2 = "^1.2.0"  # for GitSever test helpers
